linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - gocritic
    - gosimple
    - unused
    - bodyclose
    - dupl
    - misspell

linters-settings:
  govet:
    enable:
      - shadow
  dupl:
    threshold: 100
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - commentedOutCode

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck

run:
  timeout: 5m