# .goreleaser.yml
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    main: ./cmd/rss/main.go
    binary: fwrd
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: fwrd
    homepage: https://github.com/pders01/fwrd
    description: A terminal-based RSS aggregator built with Go and Charm.sh tools
    license: MIT
    skip_upload: true
    install: |
      bin.install "fwrd"
    test: |
      system "#{bin}/fwrd -version"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'