# .goreleaser.yml
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: unix
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    main: ./cmd/rss/main.go
    binary: fwrd
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/rss/main.go
    binary: fwrd
    ldflags:
      - -s -w -X main.Version={{.Version}}

brews:
  - name: fwrd
    tap:
      owner: pders01
      name: homebrew-fwrd
    homepage: https://github.com/pders01/fwrd
    description: A terminal-based RSS aggregator built with Go and Charm.sh tools
    license: MIT
    folder: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "fwrd"
    test: |
      system "#{bin}/fwrd", "-version"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
