# .goreleaser.yml
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: unix
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    main: ./cmd/rss/main.go
    binary: fwrd
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/rss/main.go
    binary: fwrd
    ldflags:
      - -s -w -X main.Version={{.Version}}

homebrew_casks:
  - name: fwrd
    repository:
      owner: pders01
      name: homebrew-fwrd
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/pders01/fwrd
    description: A terminal-based RSS aggregator built with Go and Charm.sh tools
    license: MIT
    # Default directory is Casks; keep default by omitting.
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    # For unsigned binaries, inform users how to remove quarantine on macOS.
    caveats: |
      On macOS, binaries from third-party taps may be quarantined.
      If needed, remove quarantine (adjust the path as needed):
        xattr -dr com.apple.quarantine /opt/homebrew/bin/fwrd
        xattr -dr com.apple.quarantine /usr/local/bin/fwrd
    # Generate simple cask installing the binary from archives.
    binary: fwrd

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
