# .goreleaser.yml
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    main: ./cmd/rss/main.go
    binary: fwrd
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  # Default: tar.gz for non-Windows
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format: tar.gz
    # Exclude Windows here; it has its own archive rule
    goos:
      - linux
      - darwin

  # Windows: zip
  - id: windows
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format: zip
    goos:
      - windows

# Homebrew formula step removed to avoid deprecation warnings.

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
